### ISSUE TITLE
bot goes into a connection loop when trying to start

### ISSUE THREAD

**Issue by CloroxBleach6** [domnguyen/Discord-Bot#11]
when I run the program and put in my bot token the bot won't run and tries to connect but disconnect constantly also when it does eventually connect to discord none of the commands work

**Comment by SebastianDang** [comment]
If the application is in the connection loop, then the login is failing. It will attempt to reconnect unless you cancel the request. This might be due to an invalid key. If it connects, make sure that you're only running a single instance of the application. Lingering instances of the application will affect the bot on Discord.
